name: CI Tests with Docker Compose

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      FLASK_ENV: ${{ secrets.FLASK_ENV }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_USE_SSL: ${{ secrets.MAIL_USE_SSL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Write .env.ci file
        run: |
          cat <<EOF > .ci/.env.ci
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          FLASK_ENV=${{ secrets.FLASK_ENV }}
          MAIL_SERVER=${{ secrets.MAIL_SERVER }}
          MAIL_PORT=${{ secrets.MAIL_PORT }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_USE_SSL=${{ secrets.MAIL_USE_SSL }}
          DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
          EOF
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and start services
        run: |
          docker compose -f .ci/docker-compose.yml up -d --build

      - name: Run tests
        run: docker exec flask-app pytest -v -s ./TodoAPP/tests

      - name: Show logs if failed
        if: failure()
        run: docker compose logs
